import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";
import LoginPage from "./login/page";
import RegisterPage from "./register/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
          {!!session && <Logout />}
          {/* {!session && (
            <>
            <RegisterPage/>
            </>
            )} */}
          {!session && (
              <nav>
                <div className="">
                  <div className="flex justify-between h-16 px-10 shadow items-center">
                    <div className="flex items-center space-x-8">
                      <h1 className="text-xl lg:text-2xl font-bold cursor-pointer">
                        Unibisoft
                      </h1>
                      <div className="hidden md:flex justify-around space-x-4">
                        <a href="#" className="hover:text-indigo-600 text-gray-700">
                          Home
                        </a>
                        <a href="#" className="hover:text-indigo-600 text-gray-700">
                          About
                        </a>
                        <a href="#" className="hover:text-indigo-600 text-gray-700">
                          Service
                        </a>
                        <a href="#" className="hover:text-indigo-600 text-gray-700">
                          Contact
                        </a>
                      </div>
                    </div>
                    <div className="flex space-x-4 items-center">
                    <Link href="/login" className="text-gray-800 text-sm">LOGIN</Link>
                    <Link href="/register"className="bg-indigo-600 px-4 py-2 rounded text-white hover:bg-indigo-500 text-sm" >SIGNUP</Link>
                    
                    </div>
                  </div>
                </div>
              </nav>                        
          )}
        {children}
      </body>
    </html>
  );
}
